[package]
name = "file2png"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.5"
png = "*"
sha2 = "0.9.5"
hex = "0.4"
regress = "0.4"
