name: build

on: 
  push: 
  pull_request:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      matrix:
        config:
        - name: ubuntu-build
          os: ubuntu-latest

        - name: macos-build
          os: macos-latest

        - name: windows-build
          os: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release
    
    - name: Split
      if: startswith( matrix.config.os, 'ubuntu' )
      run: |
        split ./target/release/file2png

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: file2png_${{ matrix.config.os }}_${{ github.run_id }}
        path: |
          target/release/file2png.exe
          target/release/file2png

